apiVersion: v1
kind: Service
metadata:
  name: grafana-apix2019
  namespace: apix2019
  labels:
    app: grafana-apix2019
    project: apix2019
spec:
  selector:
    app: grafana-apix2019
  type: NodePort 
  ports:
  - port: 3000
    nodePort: 30001
    protocol: TCP
