apiVersion: v1
kind: Service
metadata:
  name: mysql-apix2019
  namespace: apix2019
  labels:
    app: mysql-apix2019
    project: apix2019
spec:
  selector:
    app: mysql-apix2019
  type: NodePort 
  ports:
  - port: 3306
    nodePort: 30006
    protocol: TCP
