version: '3.7'
services:

  web:
    image: rojcosta/sirius
    container_name: web
    ports:
      - "40080:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: httpd.access
    networks:
      - apix2019

networks:
  apix2019:
    driver: bridge
