---
version: '3.6'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql_apix2019
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: apix2019
       MYSQL_DATABASE: apix2019
    networks:
      - apix2019

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_apix2019
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: 200m
    ports:
      - "9090:15672"
      - "5672:5672"
      - "25676:25676"
    networks:
      - apix2019

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elasticsearch_apix2019
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: 200m
    networks:
      - apix2019
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana_apix2019
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: 200m
    ports:
      - 5601:5601
    networks:
      - apix2019
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch_apix2019:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.1
    container_name: logstash_apix2019
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: 200m
    ports:
      - "9600:9600"
      - "9800:9800"
    networks:
      - apix2019
    depends_on:
      - elasticsearch
      - rabbitmq
    links:
      - elasticsearch:elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      RABBIT_SUGESTION_QUEUE: 'apix-sugestion-queue'
    volumes:
      - ./logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash-pipeline.conf

networks: {apix2019: {}}
