{
 "title": "APIX",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (container_memory_usage_bytes{name!=''})",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name!=''}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=''}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(job) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{job}}-usage"
    },
    {
     "expr": "avg by (job) (irate(node_cpu_seconds_total{mode=\"iowait\"}[1m])) * 100",
     "legendFormat": "{{job}}-iowait"
    }
   ]
  },
  {
   "title": "Memory Usage per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(( 100 * (sum by (job)(node_memory_MemTotal_bytes{instance=~\".*:9[1-2]00\"}) - (sum by (job)(node_memory_MemFree_bytes{instance=~\".*:9[1-2]00\"}) + sum by (job)(node_memory_Buffers_bytes{instance=~\".*:9[1-2]00\"}) + sum by (job)(node_memory_Cached_bytes{instance=~\".*:9[1-2]00\"}) ) ) / sum by (job)(node_memory_MemTotal_bytes{instance=~\".*:9[1-2]00\"})))",
     "legendFormat": "{{job}} - ram"
    },
    {
     "expr": "100 - ((node_memory_SwapFree_bytes * 100) / node_memory_SwapTotal_bytes )",
     "legendFormat": "{{job}} - swap"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])",
     "legendFormat": "{{job}}-{{device}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[5m])",
     "legendFormat": "{{job}}-{{device}}"
    }
   ]
  },
  {
   "title": "Available Storage per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (mountpoint,job) (node_filesystem_free_bytes{mountpoint!~\"^(/dev|/sys).*\"})",
     "legendFormat": "{{job}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Application Endpoint Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (probe_success{instance=~\"http.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}