apiVersion: v1
kind: Service
metadata:
  name: apix2019-microservice-finder-java
  namespace: apix2019
  labels:
    app: apix2019-microservice-finder-java
    project: apix2019
spec:
  selector:
    app: apix2019-microservice-finder-java 
  type: NodePort 
  ports:
  - port: 9200
    nodePort: 30010
    protocol: TCP
