apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apix2019-microservice-kit-java 
  namespace: apix2019
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: apix2019-microservice-kit-java
    spec:
      containers:
      - name: apix2019-microservice-kit-java
        image: XXrepoXX
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
