apiVersion: v1
kind: Service
metadata:
  name: apix2019-microservice-kit-java
  namespace: apix2019
  labels:
    app: apix2019-microservice-kit-java
    project: apix2019
spec:
  selector:
    app: apix2019-microservice-kit-java 
  type: NodePort 
  ports:
  - port: 9200
    nodePort: 30011
    protocol: TCP
