apiVersion: v1
kind: Service
metadata:
  name: apix2019-microservice-crawler-nodejs
  namespace: apix2019
  labels:
    app: apix2019-microservice-crawler-nodejs
    project: apix2019
spec:
  selector:
    app: apix2019-microservice-crawler-nodejs 
  type: NodePort 
  ports:
  - port: 9200
    nodePort: 30009
    protocol: TCP
