apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elastiseach-apix2019 
  namespace: apix2019
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: elastiseach-apix2019
    spec:
      containers:
      - name: elastiseach-apix2019
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
