apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-apix2019
  namespace: apix2019
  labels:
    app: elasticsearch-apix2019
    project: apix2019
spec:
  selector:
    app: elasticsearch-apix2019 
  type: NodePort 
  ports:
  - port: 9200
    nodePort: 30002
    protocol: TCP
