apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-apix2019 
  namespace: apix2019
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: prometheus-apix2019
    spec:
      containers:
      - name: prometheus-apix2019
        image: prom/prometheus
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
