apiVersion: v1
kind: Service
metadata:
  name: apix2019-microservice-notification-nodejs
  namespace: apix2019
  labels:
    app: apix2019-microservice-notification-nodejs
    project: apix2019
spec:
  selector:
    app: apix2019-microservice-notification-nodejs 
  type: NodePort 
  ports:
  - port: 9200
    nodePort: 30014
    protocol: TCP
