apiVersion: v1
kind: Service
metadata:
  name: logstash-apix2019
  namespace: apix2019
  labels:
    app: logstash-apix2019
    project: apix2019
spec:
  selector:
    app: logstash-apix2019
  type: NodePort 
  ports:
  - port: 9600
    nodePort: 30005
    protocol: TCP
